-- =================================================================
-- MERGE SCRIPT: Map source table to target schema
-- =================================================================
-- Source Table: Variable-driven (set TABLE_NAME below)
-- Target Table: DB_TBOON.GOLD.TARGET_CLAIMS
-- =================================================================

-- Step 0: Set the source table name variable
SET TABLE_NAME = '_730803_COMPANYNAME3_TOKIOMARINE_MD_SLDET_20250101_20251031_20251104';

-- Step 1: Create target table with standardized schema
USE DATABASE DB_TBOON;
CREATE TABLE IF NOT EXISTS GOLD.TARGET_CLAIMS (
    ACCOUNT_NUMBER VARCHAR,
    SUBGROUP_NUMBER VARCHAR,
    MEMBER_SSN VARCHAR,
    SUBSCRIBER_ID VARCHAR,
    MEMBER_SEQUENCE_NUMBER NUMBER,
    MEMBER_RELATIONSHIP_CODE VARCHAR,
    MEMBER_BIRTH_DATE DATE,
    MEMBER_FIRST_NAME VARCHAR,
    MEMBER_LAST_NAME VARCHAR,
    MEMBER_GENDER_CODE VARCHAR,
    BILLED_AMOUNT NUMBER(18,2),
    PAID_AMOUNT NUMBER(18,2),
    CLAIM_NUMBER VARCHAR,
    PAID_DATE DATE,
    SERVICE_START_DATE DATE,
    SERVICE_END_DATE DATE,
    APPROVAL_DENIAL_CODE VARCHAR,
    CLAIM_TYPE_CODE VARCHAR,
    DIAGNOSIS_CODE_1 VARCHAR,
    PROCEDURE_MODIFIER_1 VARCHAR,
    PRINCIPAL_PROCEDURE_CODE VARCHAR,
    BILLING_PROVIDER_NAME VARCHAR,
    BILLING_PROVIDER_CITY VARCHAR,
    BILLING_PROVIDER_STATE VARCHAR,
    BILLING_PROVIDER_ZIP VARCHAR,
    EMPLOYER_ZIP_CODE VARCHAR,
    MEMBER_AGE NUMBER,
    ICD_VERSION_CODE VARCHAR,
    REVENUE_CODE VARCHAR,
    STATE_SURCHARGE_AMOUNT NUMBER(18,2),
    ITS_ACS_FEE_AMOUNT NUMBER(18,2),
    ITS_SURCHARGE_AMOUNT NUMBER(18,2),
    FFS_EQUIVALENT_AMOUNT NUMBER(18,2),
    SOURCE_FILE VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Step 2: Merge data from source to target with field mapping
MERGE INTO GOLD.TARGET_CLAIMS AS tgt
USING (
    SELECT
        ACCT_NBR AS ACCOUNT_NUMBER,
        SUBGRP_NBR AS SUBGROUP_NUMBER,
        MBR_SSN AS MEMBER_SSN,
        SBSCRBR_ID AS SUBSCRIBER_ID,
        MBR_SQNC_NBR AS MEMBER_SEQUENCE_NUMBER,
        MBR_REL_CD AS MEMBER_RELATIONSHIP_CODE,
        TO_DATE(TO_TIMESTAMP(MBR_BRTH_DT)) AS MEMBER_BIRTH_DATE,
        MBR_FIRST_NM AS MEMBER_FIRST_NAME,
        MBR_LAST_NM AS MEMBER_LAST_NAME,
        MBR_GNDR_CD AS MEMBER_GENDER_CODE,
        BILLED_AMT AS BILLED_AMOUNT,
        PAID_BDC_AMT AS PAID_AMOUNT,
        CLM_NBR AS CLAIM_NUMBER,
        TO_DATE(TO_TIMESTAMP(PAID_DT)) AS PAID_DATE,
        TO_DATE(TO_TIMESTAMP(SRVC_STRT_DT)) AS SERVICE_START_DATE,
        TO_DATE(TO_TIMESTAMP(SRVC_END_DT)) AS SERVICE_END_DATE,
        APP_DENY_CD AS APPROVAL_DENIAL_CODE,
        CLM_TYPE_CD AS CLAIM_TYPE_CODE,
        TRIM(DIAG_1_CD) AS DIAGNOSIS_CODE_1,
        TRIM(PROC_MDFR_1_CD) AS PROCEDURE_MODIFIER_1,
        TRIM(PRIN_PROC_CD) AS PRINCIPAL_PROCEDURE_CODE,
        BILL_PROV_NM AS BILLING_PROVIDER_NAME,
        BILL_PROV_ADRS_CITY AS BILLING_PROVIDER_CITY,
        TRIM(BILL_PROV_ADRS_ST) AS BILLING_PROVIDER_STATE,
        BILL_PROV_ZIP_CD AS BILLING_PROVIDER_ZIP,
        EMP_ZIP_CD AS EMPLOYER_ZIP_CODE,
        MBR_AGE AS MEMBER_AGE,
        ICD_VRSN_CD AS ICD_VERSION_CODE,
        TRIM(RVNU_CD) AS REVENUE_CODE,
        ST_SURCHARGE_AMT AS STATE_SURCHARGE_AMOUNT,
        ITS_ACS_FEE_AMT AS ITS_ACS_FEE_AMOUNT,
        ITS_SURCHARGE_AMT AS ITS_SURCHARGE_AMOUNT,
        FFS_EQVLNT_AMT AS FFS_EQUIVALENT_AMOUNT,
        $TABLE_NAME AS SOURCE_FILE
    FROM IDENTIFIER('BRONZE.' || $TABLE_NAME)
) AS src
ON tgt.CLAIM_NUMBER = src.CLAIM_NUMBER
   AND tgt.SUBSCRIBER_ID = src.SUBSCRIBER_ID
   AND tgt.SERVICE_START_DATE = src.SERVICE_START_DATE
WHEN MATCHED THEN
    UPDATE SET
        tgt.ACCOUNT_NUMBER = src.ACCOUNT_NUMBER,
        tgt.SUBGROUP_NUMBER = src.SUBGROUP_NUMBER,
        tgt.MEMBER_SSN = src.MEMBER_SSN,
        tgt.MEMBER_SEQUENCE_NUMBER = src.MEMBER_SEQUENCE_NUMBER,
        tgt.MEMBER_RELATIONSHIP_CODE = src.MEMBER_RELATIONSHIP_CODE,
        tgt.MEMBER_BIRTH_DATE = src.MEMBER_BIRTH_DATE,
        tgt.MEMBER_FIRST_NAME = src.MEMBER_FIRST_NAME,
        tgt.MEMBER_LAST_NAME = src.MEMBER_LAST_NAME,
        tgt.MEMBER_GENDER_CODE = src.MEMBER_GENDER_CODE,
        tgt.BILLED_AMOUNT = src.BILLED_AMOUNT,
        tgt.PAID_AMOUNT = src.PAID_AMOUNT,
        tgt.PAID_DATE = src.PAID_DATE,
        tgt.SERVICE_END_DATE = src.SERVICE_END_DATE,
        tgt.APPROVAL_DENIAL_CODE = src.APPROVAL_DENIAL_CODE,
        tgt.CLAIM_TYPE_CODE = src.CLAIM_TYPE_CODE,
        tgt.DIAGNOSIS_CODE_1 = src.DIAGNOSIS_CODE_1,
        tgt.PROCEDURE_MODIFIER_1 = src.PROCEDURE_MODIFIER_1,
        tgt.PRINCIPAL_PROCEDURE_CODE = src.PRINCIPAL_PROCEDURE_CODE,
        tgt.BILLING_PROVIDER_NAME = src.BILLING_PROVIDER_NAME,
        tgt.BILLING_PROVIDER_CITY = src.BILLING_PROVIDER_CITY,
        tgt.BILLING_PROVIDER_STATE = src.BILLING_PROVIDER_STATE,
        tgt.BILLING_PROVIDER_ZIP = src.BILLING_PROVIDER_ZIP,
        tgt.EMPLOYER_ZIP_CODE = src.EMPLOYER_ZIP_CODE,
        tgt.MEMBER_AGE = src.MEMBER_AGE,
        tgt.ICD_VERSION_CODE = src.ICD_VERSION_CODE,
        tgt.REVENUE_CODE = src.REVENUE_CODE,
        tgt.STATE_SURCHARGE_AMOUNT = src.STATE_SURCHARGE_AMOUNT,
        tgt.ITS_ACS_FEE_AMOUNT = src.ITS_ACS_FEE_AMOUNT,
        tgt.ITS_SURCHARGE_AMOUNT = src.ITS_SURCHARGE_AMOUNT,
        tgt.FFS_EQUIVALENT_AMOUNT = src.FFS_EQUIVALENT_AMOUNT,
        tgt.SOURCE_FILE = src.SOURCE_FILE,
        tgt.LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        ACCOUNT_NUMBER, SUBGROUP_NUMBER, MEMBER_SSN, SUBSCRIBER_ID,
        MEMBER_SEQUENCE_NUMBER, MEMBER_RELATIONSHIP_CODE, MEMBER_BIRTH_DATE,
        MEMBER_FIRST_NAME, MEMBER_LAST_NAME, MEMBER_GENDER_CODE,
        BILLED_AMOUNT, PAID_AMOUNT, CLAIM_NUMBER, PAID_DATE,
        SERVICE_START_DATE, SERVICE_END_DATE, APPROVAL_DENIAL_CODE,
        CLAIM_TYPE_CODE, DIAGNOSIS_CODE_1, PROCEDURE_MODIFIER_1,
        PRINCIPAL_PROCEDURE_CODE, BILLING_PROVIDER_NAME, BILLING_PROVIDER_CITY,
        BILLING_PROVIDER_STATE, BILLING_PROVIDER_ZIP, EMPLOYER_ZIP_CODE,
        MEMBER_AGE, ICD_VERSION_CODE, REVENUE_CODE, STATE_SURCHARGE_AMOUNT,
        ITS_ACS_FEE_AMOUNT, ITS_SURCHARGE_AMOUNT, FFS_EQUIVALENT_AMOUNT,
        SOURCE_FILE, LOAD_TIMESTAMP
    )
    VALUES (
        src.ACCOUNT_NUMBER, src.SUBGROUP_NUMBER, src.MEMBER_SSN, src.SUBSCRIBER_ID,
        src.MEMBER_SEQUENCE_NUMBER, src.MEMBER_RELATIONSHIP_CODE, src.MEMBER_BIRTH_DATE,
        src.MEMBER_FIRST_NAME, src.MEMBER_LAST_NAME, src.MEMBER_GENDER_CODE,
        src.BILLED_AMOUNT, src.PAID_AMOUNT, src.CLAIM_NUMBER, src.PAID_DATE,
        src.SERVICE_START_DATE, src.SERVICE_END_DATE, src.APPROVAL_DENIAL_CODE,
        src.CLAIM_TYPE_CODE, src.DIAGNOSIS_CODE_1, src.PROCEDURE_MODIFIER_1,
        src.PRINCIPAL_PROCEDURE_CODE, src.BILLING_PROVIDER_NAME, src.BILLING_PROVIDER_CITY,
        src.BILLING_PROVIDER_STATE, src.BILLING_PROVIDER_ZIP, src.EMPLOYER_ZIP_CODE,
        src.MEMBER_AGE, src.ICD_VERSION_CODE, src.REVENUE_CODE, src.STATE_SURCHARGE_AMOUNT,
        src.ITS_ACS_FEE_AMOUNT, src.ITS_SURCHARGE_AMOUNT, src.FFS_EQUIVALENT_AMOUNT,
        src.SOURCE_FILE, CURRENT_TIMESTAMP()
    );

-- Step 3: Verify results
SELECT COUNT(*) AS TOTAL_RECORDS FROM GOLD.TARGET_CLAIMS;
SELECT * FROM GOLD.TARGET_CLAIMS LIMIT 10;
